### ISSUE TITLE
North Harbour Train line issues

### ISSUE THREAD

**Issue by Pointclearius** [MeblIkea/stormworks-custom-workbench#3]
The North Harbour tile appears to be using the old Pre industrial DLC update for the train lines and sheds. 

The trainlines should continue through the train shed however with the mod applied the tracks visually continue but a wall and buffers block the tracks inside the shed. 

The tracks physics model also is no longer aligned with the visual model further down the line, the physics model takes the train along the path of the now non existent bridge and dumps you into the sea.

This may also cause issues with other areas that had trainlines updated.

**Comment by MeblIkea** [comment]
k, it's now updated for the industrial DLC (have to make an alt version for the non-industrial DLC)
(And sorry for being late, GitHub haven't sent me the notifications for some reasons)
edit: actually, if you don't have a specific DLC, you already have the tiles for them.
